### ISSUE TITLE
Coveralls

### ISSUE THREAD

**Issue by ArielSAdamsNASA** [ArielSAdamsNASA/2021-Internship#3]
**Description**
1. Research what rules are covered.
2. Create a new workflow in GitHub to automate Coveralls on push and pull requests.
3. Use MISRA and JPL rules if applicable. 

**Helpful Links**
https://coveralls.io/

**Comment by ArielSAdamsNASA** [comment]
Try to figure out how to use only MISRA and JPL rules and where to find these rules
```

on: ["push", "pull_request"]

name: Test Coveralls

env:
  SIMULATION: native
  OMIT_DEPRECATED: false
  
jobs:
  test-cfs:
    name: Test
    runs-on: ubuntu-18.04

    strategy:
      fail-fast: false

    # Set the type of machine to run on
    env:
      BUILDTYPE: ${{ matrix.buildtype }}
      ENABLE_UNIT_TESTS: true


    steps:
      - name: Install Dependencies
        run: sudo apt-get install lcov -y

      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true

      # Setup the build system
      - name: Copy Files
        run: |
          cp ./cfe/cmake/Makefile.sample Makefile
          cp -r ./cfe/cmake/sample_defs sample_defs
      # Setup the build system
      - name: Make
        run: make

      - name: Run Tests
        run: make test

      - name: Check Coverage
        run: make lcov
        
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: build/native/default_cpu1/coverage_base.info

```
